### ISSUE TITLE
Option for, or disabling snap to hand when picking up mirror.

### ISSUE THREAD

**Issue by ocirne23** [Nirv-git/VRChat-Mods#2]
It's nice to be able to push and pull the mirror from any distance without the mirror snapping to your hand when you grab it.

People can already reset the mirror position by re-enabling it.

**Comment by Nirv-git** [comment]
This feature was added in a recent build of the mod, can you test it and let me know if it functions well for you? 

You can change this setting in Mod Settings, the QuickMenu Settings Page 2, or the ActionMenuAPI menu, under 'Extras'

**Comment by ocirne23** [comment]
works exactly as i would want it to, thanks.
