### ISSUE TITLE
Mirrors pickable button seems broken

### ISSUE THREAD

**Issue by miguelgdx** [Nirv-git/VRChat-Mods#6]
After updating to 1.6, toggling the mirror to be "Pickable" seems to be broken. The button "Pickable" does not work for any of them. It will only check for its state once the mirror is spawned and it will remain with that condition until it's destroyed and recreated again.

So for instance, if Pickable was ON, and you spawn the mirror, the mirror will remain Pickable even if you try to toggle it off many times.

**Comment by Nirv-git** [comment]
Thanks for the report, this is resolved in the current release! (Still pending VRCMG verification)
